// Generated automatically from the Excel exercise catalog.
// Do not edit this file manually.

window.EXERCISE_BLOCKS = {
  "Warm-up": [
    "Active Recovery",
    "Mobility AO protocol",
    "CARC",
    "Pull-Up",
    "Scapular Pull-Up"
  ],
  "Recovery": [
    "Active Recovery",
    "CARC"
  ],
  "Core": [
    "Floor Abs",
    "Hanging Core Strength",
    "Hanging Core Strength-Endurance",
    "Plank",
    "Side Plank",
    "Hanging Knee Raise",
    "Hanging Leg Raise",
    "Ab Wheel Rollout"
  ],
  "Forearm": [
    "Wrist curl extension",
    "Wrist curl flexion",
    "Wrist curl flexion barbell"
  ],
  "Fingers": [
    "Finger curl one arm",
    "Finger hang",
    "Campus Board",
    "Contact Strength"
  ],
  "Power": [
    "Campus Board",
    "Contact Strength"
  ],
  "Vertical pull": [
    "Pull-Up",
    "Chin-Up",
    "Scapular Pull-Up",
    "Lock-Off",
    "Assisted One-Arm Lock-Off"
  ],
  "Horizontal pull": [
    "Row",
    "Ring Row",
    "Face Pull"
  ],
  "Prehab": [
    "Face Pull",
    "Lower-Body Antagonist / Prehab",
    "Upper-Body Antagonist / Prehab",
    "External Rotation",
    "Internal Rotation",
    "Y-T-W Raise",
    "Lateral Raise"
  ],
  "Horizontal push": [
    "Push-Up",
    "Ring Push-Up",
    "Bench Press"
  ],
  "Vertical push": [
    "Dip",
    "Overhead Press",
    "Maximum Triceps Strength"
  ],
  "Arms": [
    "Maximum Biceps Strength",
    "Eccentric Biceps Curl",
    "Pletnev Biceps Protocol"
  ],
  "Hinge": [
    "Deadlift",
    "Romanian Deadlift",
    "Single-Leg Romanian Deadlift",
    "Hip Thrust",
    "Nordic Hamstring Curl"
  ],
  "Squat / lunge": [
    "Back Squat",
    "Front Squat",
    "Split Squat",
    "Bulgarian Split Squat"
  ],
  "Lower leg": [
    "Calf Raise",
    "Tibialis Raise"
  ],
  "Climbing technique": [
    "Slab Balance & Movement",
    "Complex Coordination Drills",
    "Strength in Movement / PPO (Strength-Endurance)"
  ]
};

window.EXERCISE_CATALOG = {
  "Active Recovery": {
    "default_intensity_range_percent_1rm": "25–35"
  },
  "Mobility AO protocol": {
    "default_intensity_range_percent_1rm": "25–35"
  },
  "CARC": {
    "default_intensity_range_percent_1rm": "25–35"
  },
  "Floor Abs": {
    "default_intensity_range_percent_1rm": "55–70"
  },
  "Hanging Core Strength": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Hanging Core Strength-Endurance": {
    "default_intensity_range_percent_1rm": "55–70"
  },
  "Plank": {
    "default_intensity_range_percent_1rm": "55–70"
  },
  "Side Plank": {
    "default_intensity_range_percent_1rm": "55–70"
  },
  "Hanging Knee Raise": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Hanging Leg Raise": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Ab Wheel Rollout": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Wrist curl extension": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Wrist curl flexion": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Wrist curl flexion barbell": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Finger curl one arm": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Finger hang": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Campus Board": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Contact Strength": {
    "default_intensity_range_percent_1rm": "90–100"
  },
  "Pull-Up": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Chin-Up": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Scapular Pull-Up": {
    "default_intensity_range_percent_1rm": "30–50"
  },
  "Lock-Off": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Assisted One-Arm Lock-Off": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Row": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Ring Row": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Face Pull": {
    "default_intensity_range_percent_1rm": "35–55"
  },
  "Push-Up": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Ring Push-Up": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Bench Press": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Dip": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Overhead Press": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Maximum Triceps Strength": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Maximum Biceps Strength": {
    "default_intensity_range_percent_1rm": "85–100"
  },
  "Eccentric Biceps Curl": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Pletnev Biceps Protocol": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Deadlift": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Romanian Deadlift": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Single-Leg Romanian Deadlift": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Hip Thrust": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Nordic Hamstring Curl": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Back Squat": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Front Squat": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Split Squat": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Bulgarian Split Squat": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Calf Raise": {
    "default_intensity_range_percent_1rm": "70–85"
  },
  "Tibialis Raise": {
    "default_intensity_range_percent_1rm": "55–70"
  },
  "Lower-Body Antagonist / Prehab": {
    "default_intensity_range_percent_1rm": "35–55"
  },
  "Upper-Body Antagonist / Prehab": {
    "default_intensity_range_percent_1rm": "35–55"
  },
  "External Rotation": {
    "default_intensity_range_percent_1rm": "35–55"
  },
  "Internal Rotation": {
    "default_intensity_range_percent_1rm": "35–55"
  },
  "Y-T-W Raise": {
    "default_intensity_range_percent_1rm": "30–50"
  },
  "Lateral Raise": {
    "default_intensity_range_percent_1rm": "55–70"
  },
  "Slab Balance & Movement": {
    "default_intensity_range_percent_1rm": "35–45"
  },
  "Complex Coordination Drills": {
    "default_intensity_range_percent_1rm": "50–70"
  },
  "Strength in Movement / PPO (Strength-Endurance)": {
    "default_intensity_range_percent_1rm": "55–70"
  }
};
