// Generated automatically from the Excel exercise catalog.
// Do not edit this file manually.

window.EXERCISE_BLOCKS = {
  "Warm-up": [
    "Active Recovery",
    "Mobility AO protocol",
    "CARC",
    "Pull-Up",
    "Scapular Pull-Up"
  ],
  "Recovery": [
    "Active Recovery",
    "CARC"
  ],
  "Core": [
    "Floor Abs",
    "Hanging Core Strength",
    "Hanging Core Strength-Endurance",
    "Plank",
    "Side Plank",
    "Hanging Knee Raise",
    "Hanging Leg Raise",
    "Ab Wheel Rollout"
  ],
  "Fingers": [
    "Passive two arms half crimp hang",
    "Passive one arm half crimp hang",
    "Passive two arms open hand hang",
    "Passive one arm open hand hang",
    "Passive two arms full crimp hang",
    "Passive one arm full crimp hang",
    "Passive two arms pinch grip hang",
    "Passive one arms pinch grip hang",
    "two arms three-fingers drag hang",
    "one arm three-fingers drag hang",
    "two arms two-fingers drag hang",
    "one arm two-fingers drag hang",
    "two arms one-fingers drag hang",
    "one arm one-fingers drag hang",
    "Campus Board",
    "Contact Strength"
  ],
  "Power": [
    "Campus Board",
    "Contact Strength"
  ],
  "Vertical pull": [
    "Pull-Up",
    "Chin-Up",
    "Scapular Pull-Up",
    "Lock-Off",
    "Assisted One-Arm Lock-Off"
  ],
  "Horizontal pull": [
    "Row",
    "Ring Row",
    "Face Pull"
  ],
  "Prehab": [
    "Face Pull",
    "Lower-Body Antagonist / Prehab",
    "Upper-Body Antagonist / Prehab",
    "External Rotation",
    "Internal Rotation",
    "Y-T-W Raise",
    "Lateral Raise"
  ],
  "Horizontal push": [
    "Push-Up",
    "Ring Push-Up",
    "Bench Press"
  ],
  "Vertical push": [
    "Dip",
    "Weighted Dip",
    "Overhead Press",
    "Maximum Triceps Strength"
  ],
  "Arms": [
    "Maximum Biceps Strength",
    "Eccentric Biceps Curl",
    "Pletnev Biceps Protocol"
  ],
  "Hinge": [
    "Deadlift",
    "Romanian Deadlift",
    "Single-Leg Romanian Deadlift",
    "Hip Thrust",
    "Nordic Hamstring Curl"
  ],
  "Squat / lunge": [
    "Back Squat",
    "Front Squat",
    "Split Squat",
    "Bulgarian Split Squat"
  ],
  "Lower leg": [
    "Calf Raise",
    "Tibialis Raise"
  ],
  "Climbing technique": [
    "Slab Balance & Movement",
    "Complex Coordination Drills",
    "Strength in Movement / PPO (Strength-Endurance)"
  ]
};
