from __future__ import annotations

import json
import re
from collections import OrderedDict
from pathlib import Path

from openpyxl import load_workbook


EXCEL_FILE = Path("exercise_catalog_single_table.xlsx")
OUTPUT_FILE = Path("exercise_catalog.js")


def normalize_header(value: object) -> str:
    """Normalize Excel column names."""
    if value is None:
        return ""

    return str(value).strip().lower()


def find_column(headers: list[str], column_name: str) -> int:
    """Return the index of a required Excel column."""
    normalized_name = normalize_header(column_name)

    if normalized_name not in headers:
        raise ValueError(
            f"Column '{column_name}' was not found.\n"
            f"Columns found: {headers}"
        )

    return headers.index(normalized_name)


def split_blocks(value: object) -> list[str]:
    """
    Convert the blocks cell into a list.

    Supports:
    Vertical pull
    Vertical pull, Warm-up
    Vertical pull; Warm-up
    Vertical pull | Warm-up
    """
    if value is None:
        return []

    text = str(value).strip()

    if not text:
        return []

    blocks = re.split(r"[,;|]", text)

    return [
        block.strip()
        for block in blocks
        if block.strip()
    ]


def generate_catalog() -> None:
    if not EXCEL_FILE.exists():
        raise FileNotFoundError(
            f"Excel file not found:\n{EXCEL_FILE.resolve()}"
        )

    workbook = load_workbook(
        EXCEL_FILE,
        data_only=True,
        read_only=True,
    )

    worksheet = workbook.active
    excel_rows = list(worksheet.iter_rows(values_only=True))

    if not excel_rows:
        raise ValueError("The Excel file is empty.")

    headers = [
        normalize_header(value)
        for value in excel_rows[0]
    ]

    blocks_column = find_column(headers, "blocks")
    display_name_column = find_column(headers, "display_name")

    blocks_catalog: OrderedDict[str, list[str]] = OrderedDict()

    skipped_rows = 0

    for row_number, row in enumerate(excel_rows[1:], start=2):
        blocks_value = row[blocks_column]
        display_name_value = row[display_name_column]

        if display_name_value is None:
            skipped_rows += 1
            continue

        exercise_name = str(display_name_value).strip()

        if not exercise_name:
            skipped_rows += 1
            continue

        exercise_blocks = split_blocks(blocks_value)

        if not exercise_blocks:
            print(
                f"Warning: row {row_number} has no block: "
                f"{exercise_name}"
            )
            skipped_rows += 1
            continue

        for block_name in exercise_blocks:
            if block_name not in blocks_catalog:
                blocks_catalog[block_name] = []

            if exercise_name not in blocks_catalog[block_name]:
                blocks_catalog[block_name].append(exercise_name)

    if not blocks_catalog:
        raise ValueError(
            "No catalog was generated. Check the 'blocks' and "
            "'display_name' columns."
        )

    javascript_content = (
        "// Generated automatically from the Excel exercise catalog.\n"
        "// Do not edit this file manually.\n\n"
        "window.EXERCISE_BLOCKS = "
        + json.dumps(
            blocks_catalog,
            ensure_ascii=False,
            indent=2,
        )
        + ";\n"
    )

    OUTPUT_FILE.write_text(
        javascript_content,
        encoding="utf-8",
    )

    unique_exercises = {
        exercise
        for exercises in blocks_catalog.values()
        for exercise in exercises
    }

    print(f"Created: {OUTPUT_FILE.resolve()}")
    print(f"Blocks: {len(blocks_catalog)}")
    print(f"Unique exercises: {len(unique_exercises)}")
    print(f"Skipped rows: {skipped_rows}")


if __name__ == "__main__":
    generate_catalog()